version: '3.7'

services:
  drf_starter:
    build: .
    container_name: "DRF-Starter"
    command: bash -c "python manage.py runserver 0.0.0.0:90"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "90:90"
    env_file:
      - .env


# for postgress in docker only if postgress is not running on the host

# version: '3.7'

# services:
#   drf_starter:
#     build: .
#     container_name: "DRF-Starter-Postgres"
#     command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
#     volumes:
#       - ./:/usr/src/app/
#     ports:
#       - "80:80"
#     env_file:
#       - .env
#     depends_on:
#       - postgres_db  # Wait for PostgreSQL to be ready

#   postgres_db:
#     image: postgres:15  # Use the latest stable PostgreSQL version
#     container_name: "Postgres-DB"
#     restart: always
#     environment:
#       POSTGRES_DB: general
#       POSTGRES_USER: general
#       POSTGRES_PASSWORD: general
#     ports:
#       - "5432:5432" # Map the PostgreSQL port to the host if postgress is already running on 5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

